---

- name: Jenkins and Docker
  hosts: localhost
  remote_user: ec2-user
  become: true
  
  tasks:
  - name: Install dependencies
    yum:
      name:
        - wget
        - git
        - yum-utils
      state: present

  - name: Install java 17
    yum:
      name: java-17-amazon-corretto-headless
      state: present

  - name: Download Jenkins Repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins Repo GPG key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

  - name: Install Jenkins
    yum:
      name: jenkins
      state: present

  - name: Start and Enable Jenkins
    systemd:
      name: jenkins
      state: started
      enabled: true

  - name: Sleep for 30 seconds and continue with play
    wait_for:
      timeout: 30

  - name: Get init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result

  - name: Print init password Jenkins
    debug:
      var: result.stdout

  - name: Install Docker from Amazon-linux-extras
    shell: "amazon-linux-extras install docker -y"

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present

  - name: Add jenkins user to docker group
    ansible.builtin.user:
      name: jenkins
      groups: docker
      append: yes

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: Change permissions of docker.sock
    file:
      path: "/var/run/docker.sock"
      state: file
      mode: "0777"

  - block:
    - name: Download and Unarchive maven
      unarchive:
        src:  https://downloads.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.tar.gz
        dest: /opt
        remote_src: true

    - name: Create maven symlink to /usr/bin
      file:
        src: /opt/apache-maven-3.9.10/bin/mvn
        dest: /usr/bin/mvn
        state: link

    - name: Configure maven and its environment variables
      lineinfile:
        dest: "/etc/profile.d/maven.sh"
        line: "{{ item.line }}"
        create: yes
        state: present
      loop:
        - { line: 'M2_HOME=/opt/apache-maven-3.9.10' }
        - { line: 'PATH=$PATH:$M2_HOME/bin' }

    - name: Source maven environment
      shell: "source /etc/profile.d/maven.sh"
